name: Sync IPv6 to ROS
on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨 2 点运行
  workflow_dispatch:      # 允许手动点运行按钮

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Converter
        run: python convert.py

      - name: Upload RSC to Repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add cn6.rsc
          git commit -m "Update IPv6 List" || exit 0
          git push
